## Numpy

In [2]:
import numpy as np



### The Basics of Numpy

In [23]:
a = np.array([1,2,4], dtype = 'int16')
print(a)

[1 2 4]


In [9]:
b = np.array([[2.0, 4.0, 6.0], [3.0, 2.0, 8.0]])
print(b)

[[2. 4. 6.]
 [3. 2. 8.]]


### how to check dimension 

In [16]:
a.ndim
# b.ndim

1

In [17]:
# get shape
b.shape

(2, 3)

In [18]:
b.dtype

dtype('float64')

In [24]:
a.dtype

dtype('int16')

In [26]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
# get a specific element [r,c]
a[1, 5]

13

In [29]:
# getting a specific row or column
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# other useful properties
a[0, 1:6:2]

array([2, 4, 6])

In [35]:
a[1,0] = 20
print(a)

a[:, 3]= [9,7]
print(a)

[[ 1  2  3  9  5  6  7]
 [20  9 10  9 12 13 14]]
[[ 1  2  3  9  5  6  7]
 [20  9 10  7 12 13 14]]


### 3d example

In [41]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [43]:
# how to get specifif elemnent

b[1,0,:]

array([5, 6])

In [45]:
# replacing

b[1,0,0]=20
print(b)

[[[ 1  2]
  [ 3  4]]

 [[20  6]
  [ 7  8]]]


### Initializing different types of arrays

In [54]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [55]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
np.full((2,2),77)

array([[77, 77],
       [77, 77]])

### Random decimal numbers

In [58]:
np.random.rand(4,2)  # we are not giving tuple but numbers

array([[0.63180549, 0.46408106],
       [0.77806934, 0.37998125],
       [0.94627151, 0.00825437],
       [0.92766004, 0.66743412]])

### Random Integer values

In [3]:
np.random.randint(1,21, size=(3,3))

array([[13,  2,  5],
       [18,  3, 15],
       [ 6, 12, 15]])

In [72]:
# identity matrix
np.identity(4) # diagonalna

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0 ) # rows
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [98]:
ex1 = np.ones((5,5))
print(r1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [101]:
ex1[1:-1,1:-1] = 0
print(ex1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [102]:
ex1[2,2] = 9
print(ex1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Copying arrays

In [106]:
a = np.array([1,2,3])
b=a
b[0]=10
print(b)
print(a)

[10  2  3]
[10  2  3]


In [107]:
a = np.array([1,2,3])
b=a.copy()
b[0]=10
print(b)
print(a)

[10  2  3]
[1 2 3]


### Math

In [110]:
a = np.array([2,6,7,3])
print(a)

[2 6 7 3]


In [111]:
a +2

array([4, 8, 9, 5])

In [112]:
a - 1


array([1, 5, 6, 2])

In [113]:
a*2


array([ 4, 12, 14,  6])

In [115]:
b = np.array([5,6,3,3])
print(b)

[5 6 3 3]


In [117]:
a+b


array([ 7, 12, 10,  6])

In [118]:
a**2


array([ 4, 36, 49,  9], dtype=int32)

In [119]:
np.cos(a)

array([-0.41614684,  0.96017029,  0.75390225, -0.9899925 ])

In [120]:
np.sin(a)

array([ 0.90929743, -0.2794155 ,  0.6569866 ,  0.14112001])

#### Liniar Algebra

In [123]:
%pwd
#  !pip install # with ! it allows us to use bash comends

'C:\\Users\\User\\GIT\\KeithNumpy'

In [3]:
import numpy as np
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [6]:
np.matmul(a,b) # the numbers of columns in first matrix must be equal the number of rows in second matrix

array([[6., 6.],
       [6., 6.]])

In [8]:
# the determinant of identity matrix
c = np.identity(2) # macierz jednostkowa
print(c)
np.linalg.det(c)

[[1. 0.]
 [0. 1.]]


1.0

#### Statistics

In [13]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.min(stats, axis = 1)

array([1, 4])

In [16]:
np.max(stats)

6

In [17]:
np.sum(stats)

21

In [19]:
np.sum(stats,axis = 0) # sumuje po kolumnach

array([5, 7, 9])

### Reorganizing

In [26]:
begining = np.array([[1,2,3],[4,5,6]])
print(begining.shape)

after = begining.reshape((3,2))
print(after)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


#### vertically stacking vectors

In [33]:
a = np.array([ 1, 2,  3,  9,  5,  6,  7]) # dodajemy do siebie macierze pionowo więc liczba kolumn musi być jednakowa
b = np.array([20,  9, 10,  9, 12, 13, 14])

print(np.vstack([a,b,b,a]))

[[ 1  2  3  9  5  6  7]
 [20  9 10  9 12 13 14]
 [20  9 10  9 12 13 14]
 [ 1  2  3  9  5  6  7]]


#### horizontaly

In [45]:
h1 = np.ones((2,4)) # number of rows must be the same as we adding matrixes horizontaly
h2 = np.zeros((2,2))

print(h1)
print(h2)

np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Różne

#### Load data from File


In [62]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
print(filedata.astype('int32'))
print('*')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
*
[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


#### Advanced indexing

In [64]:
filedata>=50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [67]:
(filedata[filedata>50]).astype('int32') # one can index via lists in NumPy

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [69]:
a = np.array([ 1, 2,  3,  9,  5,  6,  9])
a[[0,1,-1]]

array([1, 2, 9])

In [79]:
print(filedata.astype('int32'))

np.any(filedata > 50, axis = 0) # axis = 0 oznacza pionowo a równe jeden poziomo

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [82]:
((filedata >30) & (filedata <200))

array([[False, False, False, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])